### ISSUE TITLE
Whats the purpose of the [2] behind many of the lines

### ISSUE THREAD

**Issue by datatalking** [MalayAgr/real_python_data_cleaning_tutorial#2]
@MalayAgr I'm enjoying the blog posts written on R[ealPython](https://realpython.com/python-data-cleaning-numpy-pandas/#cleaning-the-entire-dataset-using-the-applymap-function) and had a question about the data cleaning tutorial.

Whats the reason or purpose of the randomly assigned numbers behind some of the lines and not others, its not pythonic, nor labeled and is confusing.

What would be the purpose of documenting [edit] number if that is the case as that is usually done in version control.
```
Alabama[edit]
Auburn (Auburn University)[1]
Florence (University of North Alabama)
Jacksonville (Jacksonville State University)[2]
Livingston (University of West Alabama)[2]
Montevallo (University of Montevallo)[2]
Troy (Troy University)[2]
Tuscaloosa (University of Alabama, Stillman College, Shelton State)[3][4]
```

**Comment by MalayAgr** [comment]
That's just how the data is in the file the output is from (`university_towns.txt`).


It might be that the file is created by scrapping Wikipedia and those numbers are the reference number on the Wikipedia article. `[edit]` might be the edit button on the Wikipedia article.

The file follows the following structure:

```text
State1[edit]
TownA[1]
TownB[2]
TownC[3]
State2[edit]
TownD[4]
TownE[5]
TownF[6]
```

This means that `StateA` has three towns `TownA`, `TownB` and `TownC` which have at least one university. Similarly for `StateB`.

In the tutorial, we are taking advantage of this pattern (the existence of the term `[edit]`) to get the data into a `DataFrame` so that we have the columns `State` and `RegionName`, as follows:

```
State              RegionName
State1             TownA
State1             TownB
State1             TownC
State2             TownD
State2             TownE
State2             TownF   
```

As you'll notice in the later part of the section, we remove `[edit]` and the numbers.

Hope that helps!
